[pytest]
log_cli = false
log_level = DEBUG
markers =
    ui: Tests for UI part
    ui_login_page: Tests for Login page
    ui_catalog_page: Tests for Catalog (Shop) page
    ui_product_page: Tests for Product page
    ui_header: Tests for Header
    ui_cart_page: Tests for Cart page
    ui_your_info_page: Tests for Your Info page
    ui_overview_page: Tests for Overview page
    ui_done_page: Tests for Done page
    url: Tests for URL