name: Test Runner

on: 
  workflow_dispatch:
    inputs:
      deployment_target:
        description: What to run?
        required: true
        type: choice
        options:
          - All
          - ui_login_page
          - ui_catalog_page
          - ui_product_page
          - ui_header
          - ui_cart_page
          - ui_your_info_page
          - ui_overview_page
          - ui_done_page
          - url

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.14"
    - uses: snok/install-poetry@v1
      with:
        version: 2.4.0
    - name: Install project
      uses: actions/checkout@v3
    - name: Run project
      if: "github.event.inputs.deployment_target == 'All'"
      run: poetry run pytest
      
