name: Test Runner

on: 
  workflow_dispatch:
    inputs:
      deployment_target:
        description: What to run?
        required: true
        type: choice
        options:
          - All
          - ui_login_page
          - ui_catalog_page
          - ui_product_page
          - ui_header
          - ui_cart_page
          - ui_your_info_page
          - ui_overview_page
          - ui_done_page
          - url

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Install project
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.14"
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Install Browsers
      run: playwright install
    - name: Run All tests
      if: "github.event.inputs.deployment_target == 'All'"
      run: poetry run pytest --alluredir=allure-results
      continue-on-error: true
    - name: Run ui_login_page tests
      if: "github.event.inputs.deployment_target == 'ui_login_page'"
      run: poetry run pytest -m ui_login_page --alluredir=allure-results
      continue-on-error: true
    - name: Run ui_catalog_page tests
      if: "github.event.inputs.deployment_target == 'ui_catalog_page'"
      run: poetry run pytest -m ui_catalog_page --alluredir=allure-results
      continue-on-error: true
    - name: Run ui_product_page tests
      if: "github.event.inputs.deployment_target == 'ui_product_page'"
      run: poetry run pytest -m ui_product_page --alluredir=allure-results
      continue-on-error: true
    - name: Run ui_header tests
      if: "github.event.inputs.deployment_target == 'ui_header'"
      run: poetry run pytest -m ui_header --alluredir=allure-results
      continue-on-error: true
    - name: Run ui_cart_page tests
      if: "github.event.inputs.deployment_target == 'ui_cart_page'"
      run: poetry run pytest -m ui_cart_page --alluredir=allure-results
      continue-on-error: true
    - name: Run ui_your_info_page tests
      if: "github.event.inputs.deployment_target == 'ui_your_info_page'"
      run: poetry run pytest -m ui_your_info_page --alluredir=allure-results
      continue-on-error: true
    - name: Run ui_overview_page tests
      if: "github.event.inputs.deployment_target == 'ui_overview_page'"
      run: poetry run pytest -m ui_overview_page --alluredir=allure-results
      continue-on-error: true
    - name: Run ui_done_page tests
      if: "github.event.inputs.deployment_target == 'ui_done_page'"
      run: poetry run pytest -m ui_done_page --alluredir=allure-results
      continue-on-error: true
    - name: Run url tests
      if: "github.event.inputs.deployment_target == 'url'"
      run: poetry run pytest -m url --alluredir=allure-results
      continue-on-error: true
    - name: Store allure results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results
        retention-days: 1

  publish-allure:
    name: Generate and Publish allure report
    runs-on: ubuntu-latest
    needs: run-tests
    environment:
      name: github-pages
  
    steps:
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Install allure 2.40.0
        run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.40.0/allure-2.40.0.tgz && sudo tar -zxvf allure-2.40.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.40.0/bin/allure /usr/bin/allure
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Generate allure report
        run: allure generate -c allure-results -o _site
      - name: Upload Pages artifacts
        uses: actions/upload-pages-artifact@v4
      - name: Deploy results
        id: deployment
        uses: actions/deploy-pages@v4
